### ISSUE TITLE
Omniwheel / Chassis Class

### ISSUE THREAD

**Issue by bdoget** [bdoget/robotic-arm#5]
# Description
Write a class for wheels. 
Add functionality to moveForward, left, right, back, stop, turn left, turn right, set speed.

**Comment by Arvick** [comment]
Wheel:
- added functionality for setting speed and stopping the wheel

Chassis:
- new class for managing all four wheels
- added functions for 
- setting speed, stopping
- moving forward, back, left, right

not sure how to differentiate between moving and turning left/right other than setting the speed to 0. 

Closed Issue #5
